services:
  postgres:
    image: postgres:15
    container_name: postgres-cli-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-amazon_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - pg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USER_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-network

  amazon-web-cli:
    image: mrbaloyin/amazon-web-scraper-cli:latest
    container_name: amazon-web-container-cli
    restart: "no"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-amazon_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - ./data:/app/data
    networks:
      - pg-network

volumes:
  postgres_data:

networks:
  pg-network:
